### ISSUE TITLE
Doesn't work on night mode

### ISSUE THREAD

**Issue by soberpeach** [noobj2/Anki_Change_Interface_Font#1]
It changes the font family successfully on day mode, but doesn't work during night mode. Attached pictures demonstrate what I mean. Additionally, messes with the buttons on the bottom of the screen, causing them to be cut off.

Day mode:
![day_mode](https://user-images.githubusercontent.com/36653792/104106332-79ed1380-527a-11eb-8cd8-0c380acada5b.png)

Night mode:
![night_mode](https://user-images.githubusercontent.com/36653792/104106334-7c4f6d80-527a-11eb-90a1-99915d9ef614.png)

**Comment by noobj2** [comment]
i'm aware of that -_-
but i'm really busy atm
I'll try to fix that when i get some free time

**Comment by noobj2** [comment]
welp -_- I totally forgot about this
anyways since there's a built-in night mode, fixing this would be pointless, I think
