### ISSUE TITLE
Update makes add-on not usable for 2.1.66

### ISSUE THREAD

**Issue by dochypermoose** [noobj2/Anki_Change_Interface_Font#11]
Hey there ... prior to the most recent update, the add-on was working just fine for 2.1.66. Not sure what changed, but now it says only for Anki <= 2.1.65 ... I have a few add-ons that require 2.1.66, so how do I roll this back?

**Comment by noobj2** [comment]
Hey 
Sorry my life had been really busy when you opened the issue; and I missed it.

You still need the add-on to work on 2.1.66?

**Comment by dochypermoose** [comment]
Oh no ... thanks though. I'm pretty sure it's working fine on whatever the latest version is. 

Hope everything's going well with you!
