### ISSUE TITLE
Error loading add-on upon starting up Anki on v2.1.26 macOS

### ISSUE THREAD

**Issue by skjelbreia** [noobj2/Anki_Change_Interface_Font#12]
The error states the following:

![_IMG_5679](https://github.com/noobj2/Anki-Change-Interface-Font/assets/19908884/dc3fe47b-5a1f-4713-a85c-fe42b26a3ab6)

**Comment by noobj2** [comment]
Hey,
change interface font add-on works fine on newer versions.

but if you have a reason for not updating your anki, let me know here and I'll download the older version and try to fix the add-on.

**Comment by skjelbreia** [comment]
Hello, thanks, yes I recently changed systems and tried a newer anki
version but did not like the UI changes that were implemented and wanted to
keep it the way I've had it for years.
Do you think it would run fine if I update my anki just slightly? Like say
from 2.1.26 to 2.1.35 for example? Which hopefully would preserve the UI of
2.1.26

**Comment by noobj2** [comment]
no need to update.
I don't think fixing it need a lot of time so I'll just create a separate version with the bugs fixed for anki 2.1.26 without changing the code on github.

**Comment by skjelbreia** [comment]
Okey thanks that would be great 👍 I appreciate it

**Comment by skjelbreia** [comment]
Where can I find it? If you don’t have time to change the code don’t worry about it, it would be nice to use the addon but it’s not a necessity

**Comment by noobj2** [comment]
Hey. Sorry I had a really important exam today, had to focus on that for the past month.
I'll start working on the add-ons in the next few days and will let you know when It's done.

**Comment by noobj2** [comment]
Hey @skjelbreia 
Sorry took so long.
here's a version that works on 2.1.26 (at least for me).
https://file.io/2m8hLEdz2Ydy

Test it and see if it works

**Comment by skjelbreia** [comment]
Works perfectly 👍 thanks mate!

**Comment by noobj2** [comment]
Great :D
