### ISSUE TITLE
ImportError: cannot import name `WebContent` from `aqt.webview`

### ISSUE THREAD

**Issue by ChrisCummins** [noobj2/Anki_Change_Interface_Font#2]
![image](https://user-images.githubusercontent.com/1636663/105174983-3ec0cf00-5b1b-11eb-819a-d3a38aae4f7b.png)

## Steps to reproduce

1. Install plugin using Anki.
2. Restart Anki.
3. Receive error message.

## Versions

- Anki Version 2.1.15 (442df9d6)
- Qt 5.14.2 PyQt 5.15.0
- Pop! OS 20.10

Anki was installed from Pop! shop.

**Comment by noobj2** [comment]
I'll try to them all in a couple of months -_-
sorry, too busy with life now 🤦

**Comment by noobj2** [comment]
hmmm, what a mess. forgot about this issue too. I'm really sorry for the long delay in replying -\_- but if you're still using Anki 2.1.15 let me know. I'll start working on the add-on -\_-

again, I'm really sorry -\_-

**Comment by ChrisCummins** [comment]
Hey, no worries! :-) I'm actually not using this distro anymore.

Cheers,
Chris

**Comment by noobj2** [comment]
Gonna close this then -_-
