### ISSUE TITLE
Seemingly doesn't work with mono spaced fonts anymore.

### ISSUE THREAD

**Issue by ghost** [noobj2/Anki_Change_Interface_Font#3]
It works for `Arial`, `Segoe UI`, etc.

However, I have tested four fonts: `Courier New`, `Fira Code`, `Cascadia Code`, and `Source Code Pro`, along with some of their variations. They do not show properly. The font instead defaults to `Times New Roman`.

 This leads me to believe that for some reason, mono spaced fonts are not working anymore. My Anki version is `Version ⁨2.1.48 (fb07bad3)⁩`, however what is strange is that it worked just fine for the past couple of days on the same version, for `Fira Code`.

**Comment by ghost** [comment]
So re-downloading `Fira Code` onto my system and overwriting the old font files seems to have helped. This is pretty strange to only affect mono spaced fonts. Additionally, this seems to have fixed the other mono spaced fonts too. Hmm ...

Since my issue is solved, I'll close the issue.

**Comment by ghost** [comment]
This issue has reappeared. It seems `Courier New`, which is monospaced, works again though.

**Comment by ghost** [comment]
So I guess it's an issue of working out what criteria certain monospaced fonts don't meet but others do.

**Comment by noobj2** [comment]
I tried the fonts you said don't work, but they all worked fine.
![image](https://user-images.githubusercontent.com/63994740/135608206-6764ce9d-23c5-43fa-b270-59410d404452.png)
![image](https://user-images.githubusercontent.com/63994740/135608319-592a53df-8708-4be6-97ff-b4d155e3a1e4.png)
![image](https://user-images.githubusercontent.com/63994740/135608661-e8cb9979-0c9d-4a30-8f83-0d6eca8636c4.png)

and here are some other monospaced font that I tried. all of them worked fine
![image](https://user-images.githubusercontent.com/63994740/135608813-6ce67ec8-f34f-4588-b8f3-28cd0a065c41.png)
![image](https://user-images.githubusercontent.com/63994740/135608951-19a69ddd-847a-43cf-b281-f2ff8a0f621e.png)
![image](https://user-images.githubusercontent.com/63994740/135609056-22a5ba6b-99b5-4424-b22f-decc7f38fef3.png)

I have seen some users having issues on other platforms that weren't present on windows (I'm on windows, don't have a MacBook, don't have Linux installed, so I test my add-ons on windows only)
also it's not very likely, but it might be a conflicting add-on that causes this issue (it's very unlikely tho -\_-)
have you installed any add-on in past few days that might have caused the issue?

**Comment by ghost** [comment]
Hmm, I'm on Windows 10 with Glutanimate's Heatmap and the Leaderboard add-on. It worked fine in conjunction with both of them for the past couple of days.
