### ISSUE TITLE
A word of advice: Would you mind add the ability to install fonts?

### ISSUE THREAD

**Issue by bigsmartone** [noobj2/Anki_Change_Interface_Font#4]
Thank you for your add,it makes me fell great! Please allow me to make a small suggestion: if it can customize the installation of fonts, that would be nice.The default font is still relatively basic. I hope that's not too much trouble for you.If it does, just forget it.

**Comment by noobj2** [comment]
I don't understand what you mean by "customizing the installation of fonts"
can you explain what you mean by that?

**Comment by noobj2** [comment]
I still don't know what you mean. I'll close this issue now
