### ISSUE TITLE
Crash preventing startup on 2.1.60 Qt 6

### ISSUE THREAD

**Issue by Amosnomor** [noobj2/Anki_Change_Interface_Font#7]
Ubuntu, 20.04,
Anki: Version ⁨2.1.60 (76d88073)⁩
          Python 3.9.15 Qt 6.4.2 PyQt 6.4.0

Other add-on installed: HyperTTS

Error during startup: ⁨Traceback (most recent call last):
  File "aqt.main", line 201, in __init__
  File "aqt.main", line 250, in finish_ui_setup
  File "aqt.toolbar", line 274, in draw
  File "aqt.webview", line 537, in stdHtml
  File "/home/stone/.local/share/Anki2/addons21/1431333984/Change_Font.py", line 325, in standard_css_new
    palette = theme_manager.default_palette
AttributeError: 'ThemeManager' object has no attribute 'default_palette'

**Comment by noobj2** [comment]
I'll update the add-on when I get some free time -_-

**Comment by ghost** [comment]
Any ETA for when the fix will arrive? This add-on is awesome and is a must have for me.

Thanks for all your work by the way, it's greatly appreciated!

**Comment by noobj2** [comment]
I've been pretty busy (midterm exams which will lead straight to finals)
but lemme see if I can fix it real quick

**Comment by noobj2** [comment]
I did a dirty fix (pretty much the whole code was a mess anyways).
tested it on windows and worked.

**Comment by ghost** [comment]
Thank you so much, and best of luck on your midterms and finals! :)

**Comment by Amosnomor** [comment]
Anki still failing to startup:

Error during startup: ⁨Traceback (most recent call last):
  File "aqt.main", line 201, in __init__
  File "aqt.main", line 250, in finish_ui_setup
  File "aqt.toolbar", line 274, in draw
  File "aqt.webview", line 537, in stdHtml
  File "/home/stone/.local/share/Anki2/addons21/1431333984/Change_Font.py", line 341, in standard_css_new
    color_hl_txt = palette.color(QPalette.HighlightedText).name()
NameError: name 'palette' is not defined

After removing the add-on from the filesystem, Anki debug info says:

    Anki 2.1.60 (76d88073) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
    Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.31
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-05-07 15:09:55
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2022-09-26T17:28, 'None', '']
    HyperTTS - Add speech to your flashcards ['111623432', 2023-02-24T20:35, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    111623432 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by ghost** [comment]
Try updating Anki to 2.1.62 and also make sure that you are indeed running the latest version of the add-on. I've come across no issues on MacOS. If that doesn't work it may or may not be a Linux-related issue.

**Comment by Amosnomor** [comment]
Seeing the same failure with Anki 2.1.62:

Error during startup: ⁨Traceback (most recent call last):
  File "aqt.main", line 199, in __init__
  File "aqt.main", line 248, in finish_ui_setup
  File "aqt.toolbar", line 274, in draw
  File "aqt.webview", line 537, in stdHtml
  File "/home/stone/.local/share/Anki2/addons21/1431333984/Change_Font.py", line 341, in standard_css_new
    color_hl_txt = palette.color(QPalette.HighlightedText).name()
NameError: name 'palette' is not defined

However there is an additional difference in my Anki installation.  I was unknowingly using a QT6 build of Anki on my Ubuntu 20.04 QT5 system.  Prior versions of Anki/QT6 build (e.g. 2.1.60) had a QT5 shim that worked well enough that I never noticed.  But  Anki 2.1.62/QT6  fails to start on my system without your add-on.  So I switched to a Anki/QT5 2.1.62 build, which works without _Change Interface Font_ install.
    
    Anki 2.1.62 (77dd1dc1) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
    Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.31
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-05-08 14:12:54
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2022-09-26T17:28, 'None', '']
    HyperTTS - Add speech to your flashcards ['111623432', 2023-02-24T20:35, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    111623432 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    
I am not blocked here, but was just reporting the error and following up. I will continue to monitor this issue and try other updates as they appear.

_Change Interface Font_ may not affect the problem I am trying to solve; making Chinese font(s) larger in field data columns of the deck browser.

**Comment by ghost** [comment]
Sorry to hear that the add-on is still not working. I'm not the developer so I have no clue what's exactly causing the issue.

In the meantime, if you need to make the interface font larger (which is what I understood from your comment), then you can try using [this add-on](https://ankiweb.net/shared/info/651521808) which does work in Anki 2.1.62.

If that doesn't solve what you are trying to do, then maybe try increasing the field font size from Anki itself as I have shown in the screenshot (editing font section, font size). This might even be a better solution as you won't need any add-ons and is a more granular method of controlling font size!

![image](https://user-images.githubusercontent.com/118522035/236945537-e2c740ac-99b7-4a4f-a26e-400ea6203c9c.png)

Hopefully that helps!

**Comment by noobj2** [comment]
I haven't tested the add-on on qt5 version. I'll work on it tomorrow again. This update was really rushed -_-

**Comment by noobj2** [comment]
> ear that the add-on is still not working. I'm not the devel

Hey
I updated the add-on. Can you test it and see if it works on linux?
Tested it on pretty much all the windows versions, it was working with no issue.

**Comment by Amosnomor** [comment]
Disabled all other add-ons, and it is still failing:

Error during startup: ⁨Traceback (most recent call last):
  File "aqt.main", line 199, in __init__
  File "aqt.main", line 248, in finish_ui_setup
  File "aqt.toolbar", line 274, in draw
  File "aqt.webview", line 537, in stdHtml
  File "/home/stone/.local/share/Anki2/addons21/1431333984/Change_Font.py", line 125, in standard_css_new
    color_hl_txt = palette.color(QPalette.HighlightedText).name()
NameError: name 'palette' is not defined

Also I verified that I was picking up the current version by seeing that your last changes (CHANGELOG.md and Change_font.py) were present in my local Anki addons directory.

Debug info (with Change Interface  Font removed):

    
    Anki 2.1.62 (77dd1dc1) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
    Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.31
    Flags: frz=True ao=False sv=2
    Add-ons, last update check: 2023-05-10 22:15:52
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    
    
    ===IDs of active AnkiWeb add-ons===
    
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2022-09-26T17:28, 'None', '']
    HyperTTS - Add speech to your flashcards ['111623432', 2023-02-24T20:35, 'None', mod]
    Set Font Size ['651521808', 2022-05-01T11:02, 'None', mod]

Is there anything I can do to further help debug this?

**Comment by noobj2** [comment]
I had to check anki source code -_-
something in handling the webview in linux had changed which was causing the issue.
It should be fixed now.
can you confirm if the issue has been fixed?

**Comment by Amosnomor** [comment]
Yes, it is working now on Linux.  Thank you!
