### ISSUE TITLE
Custom font not applying to review bar UI after Anki 2.1.63

### ISSUE THREAD

**Issue by ghost** [noobj2/Anki_Change_Interface_Font#8]
This is really a low priority issue as the main functionality of the add-on still works, but an issue nonetheless.

After Anki 2.1.63 the custom font does not apply to the review bar UI as seen in the below screenshot.

<img width="604" alt="image" src="https://github.com/noobj2/Anki-Change-Interface-Font/assets/118522035/e68e3c4c-5a49-48ee-a4ee-8bf151ee00c7">

The deck name and other elements have the font (Rubik) applied, but the review bar elements like the "Create Deck" button do not have the font applied whereas in Anki 2.1.62 and below the font would be applied to these elements as well.

I am currently running Anki 2.1.64 QT6 for Apple Silicon (where the issue has not changed) on MacOS 12.6.6 with the following addons:

<img width="331" alt="image" src="https://github.com/noobj2/Anki-Change-Interface-Font/assets/118522035/46bd152a-644f-43b2-8e13-8000b8193b49">

Though I doubt the other add-ons are the problem as the issue I'm describing only began after updating Anki.

I appreciate the work on the add-on, please let me know if I can do anything to troubleshoot this issue!

**Comment by noobj2** [comment]
I am on anki 2.1.65 and I don't have the issue. can you confirm if the issue persists on newer versions of anki?
![image](https://github.com/noobj2/Anki-Change-Interface-Font/assets/63994740/f2eeca5a-ab1b-46fc-b4bf-11744040a36d)
![image](https://github.com/noobj2/Anki-Change-Interface-Font/assets/63994740/fe089f39-4130-4a08-8d2b-e5b58ca976d8)

**Comment by ghost** [comment]
I'm currently running Anki version ⁨2.1.65 (aa9a734f)⁩ on Python 3.9.15 Qt 6.5.0 PyQt 6.5.0. OS is MacOS Monterey 12.6.7. Minimal mode is enabled for Anki, disabling it doesn't seem to make a difference. I also have all add-ons disabled except for Change Interface Font. The font I am using is "Rubik".

The screenshot below was taken on a fresh profile and the issue seems to persist, it may be related to an issue on my computer specifically but maybe someone on MacOS could also try and see if they can replicate this issue.

<img width="510" alt="image" src="https://github.com/noobj2/Anki-Change-Interface-Font/assets/118522035/e7d94e31-f2ef-46af-b619-9f7bb85e6670">

**Comment by noobj2** [comment]
yea that might be the reason. since I don't have a mac -_- I can't test it.
lemme see if I can find out what's causing the issue.

**Comment by noobj2** [comment]
I think it should be fixed now.
can you confirm?

**Comment by ghost** [comment]
Fixed! Thank you so much!

<img width="498" alt="image" src="https://github.com/noobj2/Anki-Change-Interface-Font/assets/118522035/6352ec35-6f88-4cd5-be20-e43b950c3191">

(I've reenabled some other add-ons here but CIF is working great!)
